version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "commentOnPullRequest"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1mkd9rjvx1zo8"
s3_prefix = "commentOnPullRequest"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
